server:
  port: ${PORT:8761}  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true
  instance:
    hostname: localhost
    status-page-url: http://${instance.hostname}:${server.port}/eureka/
